#replace with your input file
path: "./input.smi"

#k and window are mutually exclusive parameters. Just specify one of them.
k: 
window: 20

#general setting
memory: None
capacity: 40
#tautomer-related parameters
enumerate_tautomer: False
tauto_engine: 'rdkit'
pKaNorm: True
#stereoisomer-related parameters
isomer_engine: rdkit
max_confs: None
enumerate_isomer: True
mode_oe: 'classic'
mpi_np: 8
#optimization-related parameters
optimizing_engine: 'ANI2x'
use_gpu: True
gpu_idx: 0
opt_steps: 5000
convergence_threshold: 0.0001
patience: 1000
#cleanup parameters
threshold: 0.3
verbose: False
job_name: ""
